### ISSUE TITLE
rest api internal server error

### ISSUE THREAD

**Issue by ilker-aktuna** [dmike3/Hubitat#1]
I'm trying to use the xbox smartglass driver for Hubitat.

However, the rest api produces an "internal server error" when I try to connect (I have logged in and there is authentication, I can list devices and see their status)

So I tried to open an issue on the rest api Github repo. However I saw it was deprecated.
There is a web api instead of it now.

Can we migrate this to web api ?

Or do you know any solution to "internal server error" ?

**Comment by ilker-aktuna** [comment]
is this abandoned ?

**Comment by ilker-aktuna** [comment]
yes it is...

**Comment by ilker-aktuna** [comment]
it could be more kind to at least write an answer. Even "I don't know" would be better.

**Comment by dmike3** [comment]
I pulled it because Xbox made changes to their back-end system a while ago.

I recently picked up another Hubitat, and I'm reviewing code and may consider releasing a brand new driver/app for it.

It's been a few years, so I need to look over groovy.

**Comment by ilker-aktuna** [comment]
that's great
Btw, I know groovy and I can help you if you need anything on that side.
If not for development, I can at least help as a tester. Please let me know when you work on this...
